require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/transacs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Transac. As you add validations to Transac, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Transac.create! valid_attributes
      get transacs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      transac = Transac.create! valid_attributes
      get transac_url(transac)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_transac_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      transac = Transac.create! valid_attributes
      get edit_transac_url(transac)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Transac" do
        expect {
          post transacs_url, params: { transac: valid_attributes }
        }.to change(Transac, :count).by(1)
      end

      it "redirects to the created transac" do
        post transacs_url, params: { transac: valid_attributes }
        expect(response).to redirect_to(transac_url(Transac.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Transac" do
        expect {
          post transacs_url, params: { transac: invalid_attributes }
        }.to change(Transac, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post transacs_url, params: { transac: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested transac" do
        transac = Transac.create! valid_attributes
        patch transac_url(transac), params: { transac: new_attributes }
        transac.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the transac" do
        transac = Transac.create! valid_attributes
        patch transac_url(transac), params: { transac: new_attributes }
        transac.reload
        expect(response).to redirect_to(transac_url(transac))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        transac = Transac.create! valid_attributes
        patch transac_url(transac), params: { transac: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested transac" do
      transac = Transac.create! valid_attributes
      expect {
        delete transac_url(transac)
      }.to change(Transac, :count).by(-1)
    end

    it "redirects to the transacs list" do
      transac = Transac.create! valid_attributes
      delete transac_url(transac)
      expect(response).to redirect_to(transacs_url)
    end
  end
end
